//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVEDI.ServicePedidos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePedidos.IServicePedidos")]
    public interface IServicePedidos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getConsultaPedidosCliente", ReplyAction="http://tempuri.org/IServicePedidos/getConsultaPedidosClienteResponse")]
        SIVEDI.Clases.TABLAS.PedidosClienteTabla[] getConsultaPedidosCliente(int intCodigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getConsultaPedidosCliente", ReplyAction="http://tempuri.org/IServicePedidos/getConsultaPedidosClienteResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PedidosClienteTabla[]> getConsultaPedidosClienteAsync(int intCodigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getListaPreciosTabla", ReplyAction="http://tempuri.org/IServicePedidos/getListaPreciosTablaResponse")]
        SIVEDI.Clases.TABLAS.ListaPreciosTabla[] getListaPreciosTabla(int intOpcion, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getListaPreciosTabla", ReplyAction="http://tempuri.org/IServicePedidos/getListaPreciosTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosTabla[]> getListaPreciosTablaAsync(int intOpcion, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/insListaPrecios", ReplyAction="http://tempuri.org/IServicePedidos/insListaPreciosResponse")]
        int insListaPrecios(SIVEDI.Clases.ListaPrecios listaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/insListaPrecios", ReplyAction="http://tempuri.org/IServicePedidos/insListaPreciosResponse")]
        System.Threading.Tasks.Task<int> insListaPreciosAsync(SIVEDI.Clases.ListaPrecios listaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getlistaPreciosProd", ReplyAction="http://tempuri.org/IServicePedidos/getlistaPreciosProdResponse")]
        SIVEDI.Clases.TABLAS.ListaPreciosProductoComboBox[] getlistaPreciosProd(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getlistaPreciosProd", ReplyAction="http://tempuri.org/IServicePedidos/getlistaPreciosProdResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProductoComboBox[]> getlistaPreciosProdAsync(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/iuListaPreciosProducto", ReplyAction="http://tempuri.org/IServicePedidos/iuListaPreciosProductoResponse")]
        int iuListaPreciosProducto(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/iuListaPreciosProducto", ReplyAction="http://tempuri.org/IServicePedidos/iuListaPreciosProductoResponse")]
        System.Threading.Tasks.Task<int> iuListaPreciosProductoAsync(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getlistaPreciosProdExporta", ReplyAction="http://tempuri.org/IServicePedidos/getlistaPreciosProdExportaResponse")]
        SIVEDI.Clases.TABLAS.ListaPreciosProducto[] getlistaPreciosProdExporta(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getlistaPreciosProdExporta", ReplyAction="http://tempuri.org/IServicePedidos/getlistaPreciosProdExportaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProducto[]> getlistaPreciosProdExportaAsync(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoNombreLista", ReplyAction="http://tempuri.org/IServicePedidos/getProductoNombreListaResponse")]
        SIVEDI.Clases.TABLAS.ListaPreciosProducto[] getProductoNombreLista(string strNombreProducto, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoNombreLista", ReplyAction="http://tempuri.org/IServicePedidos/getProductoNombreListaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProducto[]> getProductoNombreListaAsync(string strNombreProducto, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoNombreListaProd", ReplyAction="http://tempuri.org/IServicePedidos/getProductoNombreListaProdResponse")]
        SIVEDI.Clases.TABLAS.ListaPreciosProducto[] getProductoNombreListaProd(string strNombreProducto, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoNombreListaProd", ReplyAction="http://tempuri.org/IServicePedidos/getProductoNombreListaProdResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProducto[]> getProductoNombreListaProdAsync(string strNombreProducto, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/updPreciosProdcuto", ReplyAction="http://tempuri.org/IServicePedidos/updPreciosProdcutoResponse")]
        int updPreciosProdcuto(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/updPreciosProdcuto", ReplyAction="http://tempuri.org/IServicePedidos/updPreciosProdcutoResponse")]
        System.Threading.Tasks.Task<int> updPreciosProdcutoAsync(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/DelCodigoListaPreciosProd", ReplyAction="http://tempuri.org/IServicePedidos/DelCodigoListaPreciosProdResponse")]
        int DelCodigoListaPreciosProd(int intCodigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/DelCodigoListaPreciosProd", ReplyAction="http://tempuri.org/IServicePedidos/DelCodigoListaPreciosProdResponse")]
        System.Threading.Tasks.Task<int> DelCodigoListaPreciosProdAsync(int intCodigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoNombre", ReplyAction="http://tempuri.org/IServicePedidos/getProductoNombreResponse")]
        SIVEDI.Clases.TABLAS.AsignaCodigoVenta[] getProductoNombre(string strReferencia, string strNombreProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoNombre", ReplyAction="http://tempuri.org/IServicePedidos/getProductoNombreResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.AsignaCodigoVenta[]> getProductoNombreAsync(string strReferencia, string strNombreProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getCodigoVenta", ReplyAction="http://tempuri.org/IServicePedidos/getCodigoVentaResponse")]
        SIVEDI.Clases.TABLAS.CodigoVentaTabla[] getCodigoVenta(int intOpcion, int intCodigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getCodigoVenta", ReplyAction="http://tempuri.org/IServicePedidos/getCodigoVentaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CodigoVentaTabla[]> getCodigoVentaAsync(int intOpcion, int intCodigoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/DelCodigoVenta", ReplyAction="http://tempuri.org/IServicePedidos/DelCodigoVentaResponse")]
        int DelCodigoVenta(int intCodigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/DelCodigoVenta", ReplyAction="http://tempuri.org/IServicePedidos/DelCodigoVentaResponse")]
        System.Threading.Tasks.Task<int> DelCodigoVentaAsync(int intCodigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/iuCodigoVenta", ReplyAction="http://tempuri.org/IServicePedidos/iuCodigoVentaResponse")]
        int iuCodigoVenta(SIVEDI.Clases.CodigoVenta codigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/iuCodigoVenta", ReplyAction="http://tempuri.org/IServicePedidos/iuCodigoVentaResponse")]
        System.Threading.Tasks.Task<int> iuCodigoVentaAsync(SIVEDI.Clases.CodigoVenta codigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getEquivalencias", ReplyAction="http://tempuri.org/IServicePedidos/getEquivalenciasResponse")]
        SIVEDI.Clases.TABLAS.EquivalenciasTabla[] getEquivalencias(int intOpcion, int intCodigoEquivalencia, string strCodigoSolicita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getEquivalencias", ReplyAction="http://tempuri.org/IServicePedidos/getEquivalenciasResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EquivalenciasTabla[]> getEquivalenciasAsync(int intOpcion, int intCodigoEquivalencia, string strCodigoSolicita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getCombos", ReplyAction="http://tempuri.org/IServicePedidos/getCombosResponse")]
        SIVEDI.Clases.TABLAS.CombosTabla[] getCombos(int intOpcion, int intCodigoCombo, string strCodigoVenta, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getCombos", ReplyAction="http://tempuri.org/IServicePedidos/getCombosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CombosTabla[]> getCombosAsync(int intOpcion, int intCodigoCombo, string strCodigoVenta, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoPedidos", ReplyAction="http://tempuri.org/IServicePedidos/getProductoPedidosResponse")]
        SIVEDI.Clases.TABLAS.ProductoPredidoTablas[] getProductoPedidos(string strCodigoVenta, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoPedidos", ReplyAction="http://tempuri.org/IServicePedidos/getProductoPedidosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ProductoPredidoTablas[]> getProductoPedidosAsync(string strCodigoVenta, int intCodigoListaPrecios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getClientePedido", ReplyAction="http://tempuri.org/IServicePedidos/getClientePedidoResponse")]
        SIVEDI.Clases.Cliente_pedido[] getClientePedido(string strIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getClientePedido", ReplyAction="http://tempuri.org/IServicePedidos/getClientePedidoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.Cliente_pedido[]> getClientePedidoAsync(string strIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getClienteListaPrecios", ReplyAction="http://tempuri.org/IServicePedidos/getClienteListaPreciosResponse")]
        SIVEDI.Clases.ClienteListaPrecios[] getClienteListaPrecios(int intOpcion, string strIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getClienteListaPrecios", ReplyAction="http://tempuri.org/IServicePedidos/getClienteListaPreciosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.ClienteListaPrecios[]> getClienteListaPreciosAsync(int intOpcion, string strIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoCombos", ReplyAction="http://tempuri.org/IServicePedidos/getProductoCombosResponse")]
        SIVEDI.Clases.ProductosCombo[] getProductoCombos(int intCodigoCombo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getProductoCombos", ReplyAction="http://tempuri.org/IServicePedidos/getProductoCombosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.ProductosCombo[]> getProductoCombosAsync(int intCodigoCombo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePedidosChannel : SIVEDI.ServicePedidos.IServicePedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePedidosClient : System.ServiceModel.ClientBase<SIVEDI.ServicePedidos.IServicePedidos>, SIVEDI.ServicePedidos.IServicePedidos {
        
        public ServicePedidosClient() {
        }
        
        public ServicePedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIVEDI.Clases.TABLAS.PedidosClienteTabla[] getConsultaPedidosCliente(int intCodigoCliente) {
            return base.Channel.getConsultaPedidosCliente(intCodigoCliente);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PedidosClienteTabla[]> getConsultaPedidosClienteAsync(int intCodigoCliente) {
            return base.Channel.getConsultaPedidosClienteAsync(intCodigoCliente);
        }
        
        public SIVEDI.Clases.TABLAS.ListaPreciosTabla[] getListaPreciosTabla(int intOpcion, int intCodigoListaPrecios) {
            return base.Channel.getListaPreciosTabla(intOpcion, intCodigoListaPrecios);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosTabla[]> getListaPreciosTablaAsync(int intOpcion, int intCodigoListaPrecios) {
            return base.Channel.getListaPreciosTablaAsync(intOpcion, intCodigoListaPrecios);
        }
        
        public int insListaPrecios(SIVEDI.Clases.ListaPrecios listaPrecios) {
            return base.Channel.insListaPrecios(listaPrecios);
        }
        
        public System.Threading.Tasks.Task<int> insListaPreciosAsync(SIVEDI.Clases.ListaPrecios listaPrecios) {
            return base.Channel.insListaPreciosAsync(listaPrecios);
        }
        
        public SIVEDI.Clases.TABLAS.ListaPreciosProductoComboBox[] getlistaPreciosProd(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio) {
            return base.Channel.getlistaPreciosProd(intOpcion, intCodigoProducto, intCodigoListaPrecio);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProductoComboBox[]> getlistaPreciosProdAsync(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio) {
            return base.Channel.getlistaPreciosProdAsync(intOpcion, intCodigoProducto, intCodigoListaPrecio);
        }
        
        public int iuListaPreciosProducto(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio) {
            return base.Channel.iuListaPreciosProducto(productoListaPrecio);
        }
        
        public System.Threading.Tasks.Task<int> iuListaPreciosProductoAsync(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio) {
            return base.Channel.iuListaPreciosProductoAsync(productoListaPrecio);
        }
        
        public SIVEDI.Clases.TABLAS.ListaPreciosProducto[] getlistaPreciosProdExporta(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio) {
            return base.Channel.getlistaPreciosProdExporta(intOpcion, intCodigoProducto, intCodigoListaPrecio);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProducto[]> getlistaPreciosProdExportaAsync(int intOpcion, int intCodigoProducto, int intCodigoListaPrecio) {
            return base.Channel.getlistaPreciosProdExportaAsync(intOpcion, intCodigoProducto, intCodigoListaPrecio);
        }
        
        public SIVEDI.Clases.TABLAS.ListaPreciosProducto[] getProductoNombreLista(string strNombreProducto, int intCodigoListaPrecios) {
            return base.Channel.getProductoNombreLista(strNombreProducto, intCodigoListaPrecios);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProducto[]> getProductoNombreListaAsync(string strNombreProducto, int intCodigoListaPrecios) {
            return base.Channel.getProductoNombreListaAsync(strNombreProducto, intCodigoListaPrecios);
        }
        
        public SIVEDI.Clases.TABLAS.ListaPreciosProducto[] getProductoNombreListaProd(string strNombreProducto, int intCodigoListaPrecios) {
            return base.Channel.getProductoNombreListaProd(strNombreProducto, intCodigoListaPrecios);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ListaPreciosProducto[]> getProductoNombreListaProdAsync(string strNombreProducto, int intCodigoListaPrecios) {
            return base.Channel.getProductoNombreListaProdAsync(strNombreProducto, intCodigoListaPrecios);
        }
        
        public int updPreciosProdcuto(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio) {
            return base.Channel.updPreciosProdcuto(productoListaPrecio);
        }
        
        public System.Threading.Tasks.Task<int> updPreciosProdcutoAsync(SIVEDI.Clases.ProductoListaPrecio productoListaPrecio) {
            return base.Channel.updPreciosProdcutoAsync(productoListaPrecio);
        }
        
        public int DelCodigoListaPreciosProd(int intCodigoVenta) {
            return base.Channel.DelCodigoListaPreciosProd(intCodigoVenta);
        }
        
        public System.Threading.Tasks.Task<int> DelCodigoListaPreciosProdAsync(int intCodigoVenta) {
            return base.Channel.DelCodigoListaPreciosProdAsync(intCodigoVenta);
        }
        
        public SIVEDI.Clases.TABLAS.AsignaCodigoVenta[] getProductoNombre(string strReferencia, string strNombreProducto) {
            return base.Channel.getProductoNombre(strReferencia, strNombreProducto);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.AsignaCodigoVenta[]> getProductoNombreAsync(string strReferencia, string strNombreProducto) {
            return base.Channel.getProductoNombreAsync(strReferencia, strNombreProducto);
        }
        
        public SIVEDI.Clases.TABLAS.CodigoVentaTabla[] getCodigoVenta(int intOpcion, int intCodigoProducto) {
            return base.Channel.getCodigoVenta(intOpcion, intCodigoProducto);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CodigoVentaTabla[]> getCodigoVentaAsync(int intOpcion, int intCodigoProducto) {
            return base.Channel.getCodigoVentaAsync(intOpcion, intCodigoProducto);
        }
        
        public int DelCodigoVenta(int intCodigoVenta) {
            return base.Channel.DelCodigoVenta(intCodigoVenta);
        }
        
        public System.Threading.Tasks.Task<int> DelCodigoVentaAsync(int intCodigoVenta) {
            return base.Channel.DelCodigoVentaAsync(intCodigoVenta);
        }
        
        public int iuCodigoVenta(SIVEDI.Clases.CodigoVenta codigoVenta) {
            return base.Channel.iuCodigoVenta(codigoVenta);
        }
        
        public System.Threading.Tasks.Task<int> iuCodigoVentaAsync(SIVEDI.Clases.CodigoVenta codigoVenta) {
            return base.Channel.iuCodigoVentaAsync(codigoVenta);
        }
        
        public SIVEDI.Clases.TABLAS.EquivalenciasTabla[] getEquivalencias(int intOpcion, int intCodigoEquivalencia, string strCodigoSolicita) {
            return base.Channel.getEquivalencias(intOpcion, intCodigoEquivalencia, strCodigoSolicita);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EquivalenciasTabla[]> getEquivalenciasAsync(int intOpcion, int intCodigoEquivalencia, string strCodigoSolicita) {
            return base.Channel.getEquivalenciasAsync(intOpcion, intCodigoEquivalencia, strCodigoSolicita);
        }
        
        public SIVEDI.Clases.TABLAS.CombosTabla[] getCombos(int intOpcion, int intCodigoCombo, string strCodigoVenta, int intCodigoListaPrecios) {
            return base.Channel.getCombos(intOpcion, intCodigoCombo, strCodigoVenta, intCodigoListaPrecios);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CombosTabla[]> getCombosAsync(int intOpcion, int intCodigoCombo, string strCodigoVenta, int intCodigoListaPrecios) {
            return base.Channel.getCombosAsync(intOpcion, intCodigoCombo, strCodigoVenta, intCodigoListaPrecios);
        }
        
        public SIVEDI.Clases.TABLAS.ProductoPredidoTablas[] getProductoPedidos(string strCodigoVenta, int intCodigoListaPrecios) {
            return base.Channel.getProductoPedidos(strCodigoVenta, intCodigoListaPrecios);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ProductoPredidoTablas[]> getProductoPedidosAsync(string strCodigoVenta, int intCodigoListaPrecios) {
            return base.Channel.getProductoPedidosAsync(strCodigoVenta, intCodigoListaPrecios);
        }
        
        public SIVEDI.Clases.Cliente_pedido[] getClientePedido(string strIdentificacion) {
            return base.Channel.getClientePedido(strIdentificacion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.Cliente_pedido[]> getClientePedidoAsync(string strIdentificacion) {
            return base.Channel.getClientePedidoAsync(strIdentificacion);
        }
        
        public SIVEDI.Clases.ClienteListaPrecios[] getClienteListaPrecios(int intOpcion, string strIdentificacion) {
            return base.Channel.getClienteListaPrecios(intOpcion, strIdentificacion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.ClienteListaPrecios[]> getClienteListaPreciosAsync(int intOpcion, string strIdentificacion) {
            return base.Channel.getClienteListaPreciosAsync(intOpcion, strIdentificacion);
        }
        
        public SIVEDI.Clases.ProductosCombo[] getProductoCombos(int intCodigoCombo) {
            return base.Channel.getProductoCombos(intCodigoCombo);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.ProductosCombo[]> getProductoCombosAsync(int intCodigoCombo) {
            return base.Channel.getProductoCombosAsync(intCodigoCombo);
        }
    }
}
