//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVEDI.ServicePedidos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePedidos.IServicePedidos")]
    public interface IServicePedidos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getConsultaPedidosCliente", ReplyAction="http://tempuri.org/IServicePedidos/getConsultaPedidosClienteResponse")]
        SIVEDI.Clases.TABLAS.PedidosClienteTabla[] getConsultaPedidosCliente(int intCodigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/getConsultaPedidosCliente", ReplyAction="http://tempuri.org/IServicePedidos/getConsultaPedidosClienteResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PedidosClienteTabla[]> getConsultaPedidosClienteAsync(int intCodigoCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePedidosChannel : SIVEDI.ServicePedidos.IServicePedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePedidosClient : System.ServiceModel.ClientBase<SIVEDI.ServicePedidos.IServicePedidos>, SIVEDI.ServicePedidos.IServicePedidos {
        
        public ServicePedidosClient() {
        }
        
        public ServicePedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIVEDI.Clases.TABLAS.PedidosClienteTabla[] getConsultaPedidosCliente(int intCodigoCliente) {
            return base.Channel.getConsultaPedidosCliente(intCodigoCliente);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PedidosClienteTabla[]> getConsultaPedidosClienteAsync(int intCodigoCliente) {
            return base.Channel.getConsultaPedidosClienteAsync(intCodigoCliente);
        }
    }
}
