//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVEDI.ServicioGeneral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioGeneral.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ingresaAplicativo", ReplyAction="http://tempuri.org/IService/ingresaAplicativoResponse")]
        SIVEDI.Clases.LoginUsuario ingresaAplicativo(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ingresaAplicativo", ReplyAction="http://tempuri.org/IService/ingresaAplicativoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.LoginUsuario> ingresaAplicativoAsync(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getModuloPadre", ReplyAction="http://tempuri.org/IService/getModuloPadreResponse")]
        SIVEDI.Clases.moduloPadre[] getModuloPadre(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getModuloPadre", ReplyAction="http://tempuri.org/IService/getModuloPadreResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.moduloPadre[]> getModuloPadreAsync(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getModuloHijo", ReplyAction="http://tempuri.org/IService/getModuloHijoResponse")]
        SIVEDI.Clases.moduloHijo[] getModuloHijo(int intCodigoUsuario, int intCodigoPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getModuloHijo", ReplyAction="http://tempuri.org/IService/getModuloHijoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.moduloHijo[]> getModuloHijoAsync(int intCodigoUsuario, int intCodigoPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPerfiles", ReplyAction="http://tempuri.org/IService/getPerfilesResponse")]
        SIVEDI.Clases.perfiles[] getPerfiles(int intOpcion, int intCodigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPerfiles", ReplyAction="http://tempuri.org/IService/getPerfilesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.perfiles[]> getPerfilesAsync(int intOpcion, int intCodigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insPerfiles", ReplyAction="http://tempuri.org/IService/insPerfilesResponse")]
        int insPerfiles(int intOpcion, SIVEDI.Clases.perfiles perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insPerfiles", ReplyAction="http://tempuri.org/IService/insPerfilesResponse")]
        System.Threading.Tasks.Task<int> insPerfilesAsync(int intOpcion, SIVEDI.Clases.perfiles perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUsuarios", ReplyAction="http://tempuri.org/IService/getUsuariosResponse")]
        SIVEDI.Clases.TABLAS.usuariosTabla[] getUsuarios(int intOpcion, string LoginUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUsuarios", ReplyAction="http://tempuri.org/IService/getUsuariosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.usuariosTabla[]> getUsuariosAsync(int intOpcion, string LoginUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insUsuarios", ReplyAction="http://tempuri.org/IService/insUsuariosResponse")]
        int insUsuarios(SIVEDI.Clases.usuarios usuarioModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insUsuarios", ReplyAction="http://tempuri.org/IService/insUsuariosResponse")]
        System.Threading.Tasks.Task<int> insUsuariosAsync(SIVEDI.Clases.usuarios usuarioModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getTiposDocumento", ReplyAction="http://tempuri.org/IService/getTiposDocumentoResponse")]
        SIVEDI.Clases.TABLAS.tipoDocumentoTabla[] getTiposDocumento(int intOpcion, int intCodigoTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getTiposDocumento", ReplyAction="http://tempuri.org/IService/getTiposDocumentoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.tipoDocumentoTabla[]> getTiposDocumentoAsync(int intOpcion, int intCodigoTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insTipoDocumento", ReplyAction="http://tempuri.org/IService/insTipoDocumentoResponse")]
        int insTipoDocumento(SIVEDI.Clases.TipoDocumento TipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insTipoDocumento", ReplyAction="http://tempuri.org/IService/insTipoDocumentoResponse")]
        System.Threading.Tasks.Task<int> insTipoDocumentoAsync(SIVEDI.Clases.TipoDocumento TipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getTipoCliente", ReplyAction="http://tempuri.org/IService/getTipoClienteResponse")]
        SIVEDI.Clases.TABLAS.TipoClienteTabla[] getTipoCliente(int intOpcion, int intCodigoTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getTipoCliente", ReplyAction="http://tempuri.org/IService/getTipoClienteResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TipoClienteTabla[]> getTipoClienteAsync(int intOpcion, int intCodigoTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insTipoCliente", ReplyAction="http://tempuri.org/IService/insTipoClienteResponse")]
        int insTipoCliente(SIVEDI.Clases.TipoCliente tipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insTipoCliente", ReplyAction="http://tempuri.org/IService/insTipoClienteResponse")]
        System.Threading.Tasks.Task<int> insTipoClienteAsync(SIVEDI.Clases.TipoCliente tipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUnidadMedida", ReplyAction="http://tempuri.org/IService/getUnidadMedidaResponse")]
        SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[] getUnidadMedida(int intOpcion, int intCodigoUnidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUnidadMedida", ReplyAction="http://tempuri.org/IService/getUnidadMedidaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[]> getUnidadMedidaAsync(int intOpcion, int intCodigoUnidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insUnidadMedida", ReplyAction="http://tempuri.org/IService/insUnidadMedidaResponse")]
        int insUnidadMedida(SIVEDI.Clases.UnidadMedida unidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insUnidadMedida", ReplyAction="http://tempuri.org/IService/insUnidadMedidaResponse")]
        System.Threading.Tasks.Task<int> insUnidadMedidaAsync(SIVEDI.Clases.UnidadMedida unidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGeneros", ReplyAction="http://tempuri.org/IService/GetGenerosResponse")]
        SIVEDI.Clases.TABLAS.GenerosTabla[] GetGeneros(int intOpcion, int intCodigoGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGeneros", ReplyAction="http://tempuri.org/IService/GetGenerosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.GenerosTabla[]> GetGenerosAsync(int intOpcion, int intCodigoGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insGeneros", ReplyAction="http://tempuri.org/IService/insGenerosResponse")]
        int insGeneros(SIVEDI.Clases.Generos generos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insGeneros", ReplyAction="http://tempuri.org/IService/insGenerosResponse")]
        System.Threading.Tasks.Task<int> insGenerosAsync(SIVEDI.Clases.Generos generos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getformasIngreso", ReplyAction="http://tempuri.org/IService/getformasIngresoResponse")]
        SIVEDI.Clases.TABLAS.FormasIngresoTabla[] getformasIngreso(int intOpcion, int intCodigoFormaIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getformasIngreso", ReplyAction="http://tempuri.org/IService/getformasIngresoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.FormasIngresoTabla[]> getformasIngresoAsync(int intOpcion, int intCodigoFormaIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insFormasIngreso", ReplyAction="http://tempuri.org/IService/insFormasIngresoResponse")]
        int insFormasIngreso(SIVEDI.Clases.formasIngreso formasIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insFormasIngreso", ReplyAction="http://tempuri.org/IService/insFormasIngresoResponse")]
        System.Threading.Tasks.Task<int> insFormasIngresoAsync(SIVEDI.Clases.formasIngreso formasIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEstadoCivil", ReplyAction="http://tempuri.org/IService/getEstadoCivilResponse")]
        SIVEDI.Clases.TABLAS.EstadoCivilTabla[] getEstadoCivil(int intOpcion, int intCodigoEstadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEstadoCivil", ReplyAction="http://tempuri.org/IService/getEstadoCivilResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoCivilTabla[]> getEstadoCivilAsync(int intOpcion, int intCodigoEstadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insEstadoCivil", ReplyAction="http://tempuri.org/IService/insEstadoCivilResponse")]
        int insEstadoCivil(SIVEDI.Clases.EstadoCivil estadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insEstadoCivil", ReplyAction="http://tempuri.org/IService/insEstadoCivilResponse")]
        System.Threading.Tasks.Task<int> insEstadoCivilAsync(SIVEDI.Clases.EstadoCivil estadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEstadoActividad", ReplyAction="http://tempuri.org/IService/getEstadoActividadResponse")]
        SIVEDI.Clases.TABLAS.EstadoActividadTabla[] getEstadoActividad(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEstadoActividad", ReplyAction="http://tempuri.org/IService/getEstadoActividadResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoActividadTabla[]> getEstadoActividadAsync(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEstadoActividadCamposTabla", ReplyAction="http://tempuri.org/IService/getEstadoActividadCamposTablaResponse")]
        SIVEDI.Clases.EstadoActividad getEstadoActividadCamposTabla(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getEstadoActividadCamposTabla", ReplyAction="http://tempuri.org/IService/getEstadoActividadCamposTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.EstadoActividad> getEstadoActividadCamposTablaAsync(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insEstadoActividad", ReplyAction="http://tempuri.org/IService/insEstadoActividadResponse")]
        int insEstadoActividad(SIVEDI.Clases.EstadoActividad estadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insEstadoActividad", ReplyAction="http://tempuri.org/IService/insEstadoActividadResponse")]
        System.Threading.Tasks.Task<int> insEstadoActividadAsync(SIVEDI.Clases.EstadoActividad estadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCampanas", ReplyAction="http://tempuri.org/IService/getCampanasResponse")]
        SIVEDI.Clases.TABLAS.CampanasTabla[] getCampanas(int intOpcion, int intCodigoCampana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCampanas", ReplyAction="http://tempuri.org/IService/getCampanasResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CampanasTabla[]> getCampanasAsync(int intOpcion, int intCodigoCampana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insCampanas", ReplyAction="http://tempuri.org/IService/insCampanasResponse")]
        int insCampanas(SIVEDI.Clases.campanas Campanas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insCampanas", ReplyAction="http://tempuri.org/IService/insCampanasResponse")]
        System.Threading.Tasks.Task<int> insCampanasAsync(SIVEDI.Clases.campanas Campanas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPaises", ReplyAction="http://tempuri.org/IService/getPaisesResponse")]
        SIVEDI.Clases.TABLAS.PaisTabla[] getPaises(int intOpcion, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getPaises", ReplyAction="http://tempuri.org/IService/getPaisesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PaisTabla[]> getPaisesAsync(int intOpcion, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insPaises", ReplyAction="http://tempuri.org/IService/insPaisesResponse")]
        int insPaises(SIVEDI.Clases.Pais pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insPaises", ReplyAction="http://tempuri.org/IService/insPaisesResponse")]
        System.Threading.Tasks.Task<int> insPaisesAsync(SIVEDI.Clases.Pais pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDepartamentos", ReplyAction="http://tempuri.org/IService/getDepartamentosResponse")]
        SIVEDI.Clases.TABLAS.DepartamentoTabla[] getDepartamentos(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDepartamentos", ReplyAction="http://tempuri.org/IService/getDepartamentosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.DepartamentoTabla[]> getDepartamentosAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDepartamentoTabla", ReplyAction="http://tempuri.org/IService/getDepartamentoTablaResponse")]
        SIVEDI.Clases.Departamentos getDepartamentoTabla(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getDepartamentoTabla", ReplyAction="http://tempuri.org/IService/getDepartamentoTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.Departamentos> getDepartamentoTablaAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insDepartamento", ReplyAction="http://tempuri.org/IService/insDepartamentoResponse")]
        int insDepartamento(SIVEDI.Clases.Departamentos departamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insDepartamento", ReplyAction="http://tempuri.org/IService/insDepartamentoResponse")]
        System.Threading.Tasks.Task<int> insDepartamentoAsync(SIVEDI.Clases.Departamentos departamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCiudades", ReplyAction="http://tempuri.org/IService/getCiudadesResponse")]
        SIVEDI.Clases.TABLAS.CiudadesTabla[] getCiudades(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCiudades", ReplyAction="http://tempuri.org/IService/getCiudadesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CiudadesTabla[]> getCiudadesAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCiudadesTabla", ReplyAction="http://tempuri.org/IService/getCiudadesTablaResponse")]
        SIVEDI.Clases.Ciudades getCiudadesTabla(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getCiudadesTabla", ReplyAction="http://tempuri.org/IService/getCiudadesTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.Ciudades> getCiudadesTablaAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insCiudades", ReplyAction="http://tempuri.org/IService/insCiudadesResponse")]
        int insCiudades(SIVEDI.Clases.Ciudades ciudades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insCiudades", ReplyAction="http://tempuri.org/IService/insCiudadesResponse")]
        System.Threading.Tasks.Task<int> insCiudadesAsync(SIVEDI.Clases.Ciudades ciudades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getClaseResponsable", ReplyAction="http://tempuri.org/IService/getClaseResponsableResponse")]
        SIVEDI.Clases.TABLAS.ClaseResponsableTabla[] getClaseResponsable(int intOpcion, int intCodigoClaseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getClaseResponsable", ReplyAction="http://tempuri.org/IService/getClaseResponsableResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ClaseResponsableTabla[]> getClaseResponsableAsync(int intOpcion, int intCodigoClaseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insClaseResponsable", ReplyAction="http://tempuri.org/IService/insClaseResponsableResponse")]
        int insClaseResponsable(SIVEDI.Clases.ClaseResponsable claseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insClaseResponsable", ReplyAction="http://tempuri.org/IService/insClaseResponsableResponse")]
        System.Threading.Tasks.Task<int> insClaseResponsableAsync(SIVEDI.Clases.ClaseResponsable claseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getResponsableTerritorio", ReplyAction="http://tempuri.org/IService/getResponsableTerritorioResponse")]
        SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[] getResponsableTerritorio(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getResponsableTerritorio", ReplyAction="http://tempuri.org/IService/getResponsableTerritorioResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[]> getResponsableTerritorioAsync(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insResponsableTerritorio", ReplyAction="http://tempuri.org/IService/insResponsableTerritorioResponse")]
        int insResponsableTerritorio(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insResponsableTerritorio", ReplyAction="http://tempuri.org/IService/insResponsableTerritorioResponse")]
        System.Threading.Tasks.Task<int> insResponsableTerritorioAsync(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getResponsableFiltro", ReplyAction="http://tempuri.org/IService/getResponsableFiltroResponse")]
        SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[] getResponsableFiltro(string strIdentificacion, string strNombreResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getResponsableFiltro", ReplyAction="http://tempuri.org/IService/getResponsableFiltroResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[]> getResponsableFiltroAsync(string strIdentificacion, string strNombreResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getRegionales", ReplyAction="http://tempuri.org/IService/getRegionalesResponse")]
        SIVEDI.Clases.TABLAS.RegionalesTabla[] getRegionales(int intOpcion, int intCodigoRegional, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getRegionales", ReplyAction="http://tempuri.org/IService/getRegionalesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.RegionalesTabla[]> getRegionalesAsync(int intOpcion, int intCodigoRegional, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insRegionales", ReplyAction="http://tempuri.org/IService/insRegionalesResponse")]
        int insRegionales(SIVEDI.Clases.Regionales regionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/insRegionales", ReplyAction="http://tempuri.org/IService/insRegionalesResponse")]
        System.Threading.Tasks.Task<int> insRegionalesAsync(SIVEDI.Clases.Regionales regionales);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SIVEDI.ServicioGeneral.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SIVEDI.ServicioGeneral.IService>, SIVEDI.ServicioGeneral.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIVEDI.Clases.LoginUsuario ingresaAplicativo(string strUser, string strPassword) {
            return base.Channel.ingresaAplicativo(strUser, strPassword);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.LoginUsuario> ingresaAplicativoAsync(string strUser, string strPassword) {
            return base.Channel.ingresaAplicativoAsync(strUser, strPassword);
        }
        
        public SIVEDI.Clases.moduloPadre[] getModuloPadre(int intOpcion) {
            return base.Channel.getModuloPadre(intOpcion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.moduloPadre[]> getModuloPadreAsync(int intOpcion) {
            return base.Channel.getModuloPadreAsync(intOpcion);
        }
        
        public SIVEDI.Clases.moduloHijo[] getModuloHijo(int intCodigoUsuario, int intCodigoPadre) {
            return base.Channel.getModuloHijo(intCodigoUsuario, intCodigoPadre);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.moduloHijo[]> getModuloHijoAsync(int intCodigoUsuario, int intCodigoPadre) {
            return base.Channel.getModuloHijoAsync(intCodigoUsuario, intCodigoPadre);
        }
        
        public SIVEDI.Clases.perfiles[] getPerfiles(int intOpcion, int intCodigoPerfil) {
            return base.Channel.getPerfiles(intOpcion, intCodigoPerfil);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.perfiles[]> getPerfilesAsync(int intOpcion, int intCodigoPerfil) {
            return base.Channel.getPerfilesAsync(intOpcion, intCodigoPerfil);
        }
        
        public int insPerfiles(int intOpcion, SIVEDI.Clases.perfiles perfil) {
            return base.Channel.insPerfiles(intOpcion, perfil);
        }
        
        public System.Threading.Tasks.Task<int> insPerfilesAsync(int intOpcion, SIVEDI.Clases.perfiles perfil) {
            return base.Channel.insPerfilesAsync(intOpcion, perfil);
        }
        
        public SIVEDI.Clases.TABLAS.usuariosTabla[] getUsuarios(int intOpcion, string LoginUsuario) {
            return base.Channel.getUsuarios(intOpcion, LoginUsuario);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.usuariosTabla[]> getUsuariosAsync(int intOpcion, string LoginUsuario) {
            return base.Channel.getUsuariosAsync(intOpcion, LoginUsuario);
        }
        
        public int insUsuarios(SIVEDI.Clases.usuarios usuarioModel) {
            return base.Channel.insUsuarios(usuarioModel);
        }
        
        public System.Threading.Tasks.Task<int> insUsuariosAsync(SIVEDI.Clases.usuarios usuarioModel) {
            return base.Channel.insUsuariosAsync(usuarioModel);
        }
        
        public SIVEDI.Clases.TABLAS.tipoDocumentoTabla[] getTiposDocumento(int intOpcion, int intCodigoTipoDocumento) {
            return base.Channel.getTiposDocumento(intOpcion, intCodigoTipoDocumento);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.tipoDocumentoTabla[]> getTiposDocumentoAsync(int intOpcion, int intCodigoTipoDocumento) {
            return base.Channel.getTiposDocumentoAsync(intOpcion, intCodigoTipoDocumento);
        }
        
        public int insTipoDocumento(SIVEDI.Clases.TipoDocumento TipoDocumento) {
            return base.Channel.insTipoDocumento(TipoDocumento);
        }
        
        public System.Threading.Tasks.Task<int> insTipoDocumentoAsync(SIVEDI.Clases.TipoDocumento TipoDocumento) {
            return base.Channel.insTipoDocumentoAsync(TipoDocumento);
        }
        
        public SIVEDI.Clases.TABLAS.TipoClienteTabla[] getTipoCliente(int intOpcion, int intCodigoTipoCliente) {
            return base.Channel.getTipoCliente(intOpcion, intCodigoTipoCliente);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TipoClienteTabla[]> getTipoClienteAsync(int intOpcion, int intCodigoTipoCliente) {
            return base.Channel.getTipoClienteAsync(intOpcion, intCodigoTipoCliente);
        }
        
        public int insTipoCliente(SIVEDI.Clases.TipoCliente tipoCliente) {
            return base.Channel.insTipoCliente(tipoCliente);
        }
        
        public System.Threading.Tasks.Task<int> insTipoClienteAsync(SIVEDI.Clases.TipoCliente tipoCliente) {
            return base.Channel.insTipoClienteAsync(tipoCliente);
        }
        
        public SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[] getUnidadMedida(int intOpcion, int intCodigoUnidadMedida) {
            return base.Channel.getUnidadMedida(intOpcion, intCodigoUnidadMedida);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[]> getUnidadMedidaAsync(int intOpcion, int intCodigoUnidadMedida) {
            return base.Channel.getUnidadMedidaAsync(intOpcion, intCodigoUnidadMedida);
        }
        
        public int insUnidadMedida(SIVEDI.Clases.UnidadMedida unidadMedida) {
            return base.Channel.insUnidadMedida(unidadMedida);
        }
        
        public System.Threading.Tasks.Task<int> insUnidadMedidaAsync(SIVEDI.Clases.UnidadMedida unidadMedida) {
            return base.Channel.insUnidadMedidaAsync(unidadMedida);
        }
        
        public SIVEDI.Clases.TABLAS.GenerosTabla[] GetGeneros(int intOpcion, int intCodigoGenero) {
            return base.Channel.GetGeneros(intOpcion, intCodigoGenero);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.GenerosTabla[]> GetGenerosAsync(int intOpcion, int intCodigoGenero) {
            return base.Channel.GetGenerosAsync(intOpcion, intCodigoGenero);
        }
        
        public int insGeneros(SIVEDI.Clases.Generos generos) {
            return base.Channel.insGeneros(generos);
        }
        
        public System.Threading.Tasks.Task<int> insGenerosAsync(SIVEDI.Clases.Generos generos) {
            return base.Channel.insGenerosAsync(generos);
        }
        
        public SIVEDI.Clases.TABLAS.FormasIngresoTabla[] getformasIngreso(int intOpcion, int intCodigoFormaIngreso) {
            return base.Channel.getformasIngreso(intOpcion, intCodigoFormaIngreso);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.FormasIngresoTabla[]> getformasIngresoAsync(int intOpcion, int intCodigoFormaIngreso) {
            return base.Channel.getformasIngresoAsync(intOpcion, intCodigoFormaIngreso);
        }
        
        public int insFormasIngreso(SIVEDI.Clases.formasIngreso formasIngreso) {
            return base.Channel.insFormasIngreso(formasIngreso);
        }
        
        public System.Threading.Tasks.Task<int> insFormasIngresoAsync(SIVEDI.Clases.formasIngreso formasIngreso) {
            return base.Channel.insFormasIngresoAsync(formasIngreso);
        }
        
        public SIVEDI.Clases.TABLAS.EstadoCivilTabla[] getEstadoCivil(int intOpcion, int intCodigoEstadoCivil) {
            return base.Channel.getEstadoCivil(intOpcion, intCodigoEstadoCivil);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoCivilTabla[]> getEstadoCivilAsync(int intOpcion, int intCodigoEstadoCivil) {
            return base.Channel.getEstadoCivilAsync(intOpcion, intCodigoEstadoCivil);
        }
        
        public int insEstadoCivil(SIVEDI.Clases.EstadoCivil estadoCivil) {
            return base.Channel.insEstadoCivil(estadoCivil);
        }
        
        public System.Threading.Tasks.Task<int> insEstadoCivilAsync(SIVEDI.Clases.EstadoCivil estadoCivil) {
            return base.Channel.insEstadoCivilAsync(estadoCivil);
        }
        
        public SIVEDI.Clases.TABLAS.EstadoActividadTabla[] getEstadoActividad(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividad(intOpcion, intCodigoEstadoActividad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoActividadTabla[]> getEstadoActividadAsync(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividadAsync(intOpcion, intCodigoEstadoActividad);
        }
        
        public SIVEDI.Clases.EstadoActividad getEstadoActividadCamposTabla(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividadCamposTabla(intOpcion, intCodigoEstadoActividad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.EstadoActividad> getEstadoActividadCamposTablaAsync(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividadCamposTablaAsync(intOpcion, intCodigoEstadoActividad);
        }
        
        public int insEstadoActividad(SIVEDI.Clases.EstadoActividad estadoActividad) {
            return base.Channel.insEstadoActividad(estadoActividad);
        }
        
        public System.Threading.Tasks.Task<int> insEstadoActividadAsync(SIVEDI.Clases.EstadoActividad estadoActividad) {
            return base.Channel.insEstadoActividadAsync(estadoActividad);
        }
        
        public SIVEDI.Clases.TABLAS.CampanasTabla[] getCampanas(int intOpcion, int intCodigoCampana) {
            return base.Channel.getCampanas(intOpcion, intCodigoCampana);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CampanasTabla[]> getCampanasAsync(int intOpcion, int intCodigoCampana) {
            return base.Channel.getCampanasAsync(intOpcion, intCodigoCampana);
        }
        
        public int insCampanas(SIVEDI.Clases.campanas Campanas) {
            return base.Channel.insCampanas(Campanas);
        }
        
        public System.Threading.Tasks.Task<int> insCampanasAsync(SIVEDI.Clases.campanas Campanas) {
            return base.Channel.insCampanasAsync(Campanas);
        }
        
        public SIVEDI.Clases.TABLAS.PaisTabla[] getPaises(int intOpcion, int intCodigoPais) {
            return base.Channel.getPaises(intOpcion, intCodigoPais);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PaisTabla[]> getPaisesAsync(int intOpcion, int intCodigoPais) {
            return base.Channel.getPaisesAsync(intOpcion, intCodigoPais);
        }
        
        public int insPaises(SIVEDI.Clases.Pais pais) {
            return base.Channel.insPaises(pais);
        }
        
        public System.Threading.Tasks.Task<int> insPaisesAsync(SIVEDI.Clases.Pais pais) {
            return base.Channel.insPaisesAsync(pais);
        }
        
        public SIVEDI.Clases.TABLAS.DepartamentoTabla[] getDepartamentos(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentos(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.DepartamentoTabla[]> getDepartamentosAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentosAsync(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public SIVEDI.Clases.Departamentos getDepartamentoTabla(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentoTabla(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.Departamentos> getDepartamentoTablaAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentoTablaAsync(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public int insDepartamento(SIVEDI.Clases.Departamentos departamentos) {
            return base.Channel.insDepartamento(departamentos);
        }
        
        public System.Threading.Tasks.Task<int> insDepartamentoAsync(SIVEDI.Clases.Departamentos departamentos) {
            return base.Channel.insDepartamentoAsync(departamentos);
        }
        
        public SIVEDI.Clases.TABLAS.CiudadesTabla[] getCiudades(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudades(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CiudadesTabla[]> getCiudadesAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudadesAsync(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public SIVEDI.Clases.Ciudades getCiudadesTabla(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudadesTabla(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.Ciudades> getCiudadesTablaAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudadesTablaAsync(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public int insCiudades(SIVEDI.Clases.Ciudades ciudades) {
            return base.Channel.insCiudades(ciudades);
        }
        
        public System.Threading.Tasks.Task<int> insCiudadesAsync(SIVEDI.Clases.Ciudades ciudades) {
            return base.Channel.insCiudadesAsync(ciudades);
        }
        
        public SIVEDI.Clases.TABLAS.ClaseResponsableTabla[] getClaseResponsable(int intOpcion, int intCodigoClaseResponsable) {
            return base.Channel.getClaseResponsable(intOpcion, intCodigoClaseResponsable);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ClaseResponsableTabla[]> getClaseResponsableAsync(int intOpcion, int intCodigoClaseResponsable) {
            return base.Channel.getClaseResponsableAsync(intOpcion, intCodigoClaseResponsable);
        }
        
        public int insClaseResponsable(SIVEDI.Clases.ClaseResponsable claseResponsable) {
            return base.Channel.insClaseResponsable(claseResponsable);
        }
        
        public System.Threading.Tasks.Task<int> insClaseResponsableAsync(SIVEDI.Clases.ClaseResponsable claseResponsable) {
            return base.Channel.insClaseResponsableAsync(claseResponsable);
        }
        
        public SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[] getResponsableTerritorio(int intOpcion) {
            return base.Channel.getResponsableTerritorio(intOpcion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[]> getResponsableTerritorioAsync(int intOpcion) {
            return base.Channel.getResponsableTerritorioAsync(intOpcion);
        }
        
        public int insResponsableTerritorio(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio) {
            return base.Channel.insResponsableTerritorio(responsableTerritorio);
        }
        
        public System.Threading.Tasks.Task<int> insResponsableTerritorioAsync(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio) {
            return base.Channel.insResponsableTerritorioAsync(responsableTerritorio);
        }
        
        public SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[] getResponsableFiltro(string strIdentificacion, string strNombreResponsable) {
            return base.Channel.getResponsableFiltro(strIdentificacion, strNombreResponsable);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[]> getResponsableFiltroAsync(string strIdentificacion, string strNombreResponsable) {
            return base.Channel.getResponsableFiltroAsync(strIdentificacion, strNombreResponsable);
        }
        
        public SIVEDI.Clases.TABLAS.RegionalesTabla[] getRegionales(int intOpcion, int intCodigoRegional, int intCodigoPais) {
            return base.Channel.getRegionales(intOpcion, intCodigoRegional, intCodigoPais);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.RegionalesTabla[]> getRegionalesAsync(int intOpcion, int intCodigoRegional, int intCodigoPais) {
            return base.Channel.getRegionalesAsync(intOpcion, intCodigoRegional, intCodigoPais);
        }
        
        public int insRegionales(SIVEDI.Clases.Regionales regionales) {
            return base.Channel.insRegionales(regionales);
        }
        
        public System.Threading.Tasks.Task<int> insRegionalesAsync(SIVEDI.Clases.Regionales regionales) {
            return base.Channel.insRegionalesAsync(regionales);
        }
    }
}
