//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVEDI.ServicioGeneral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioGeneral.IServicioGeneral")]
    public interface IServicioGeneral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/ingresaAplicativo", ReplyAction="http://tempuri.org/IServicioGeneral/ingresaAplicativoResponse")]
        SIVEDI.Clases.LoginUsuario ingresaAplicativo(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/ingresaAplicativo", ReplyAction="http://tempuri.org/IServicioGeneral/ingresaAplicativoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.LoginUsuario> ingresaAplicativoAsync(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getModuloPadre", ReplyAction="http://tempuri.org/IServicioGeneral/getModuloPadreResponse")]
        SIVEDI.Clases.moduloPadre[] getModuloPadre(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getModuloPadre", ReplyAction="http://tempuri.org/IServicioGeneral/getModuloPadreResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.moduloPadre[]> getModuloPadreAsync(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getModuloHijo", ReplyAction="http://tempuri.org/IServicioGeneral/getModuloHijoResponse")]
        SIVEDI.Clases.moduloHijo[] getModuloHijo(int intCodigoUsuario, int intCodigoPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getModuloHijo", ReplyAction="http://tempuri.org/IServicioGeneral/getModuloHijoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.moduloHijo[]> getModuloHijoAsync(int intCodigoUsuario, int intCodigoPadre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getPerfiles", ReplyAction="http://tempuri.org/IServicioGeneral/getPerfilesResponse")]
        SIVEDI.Clases.perfiles[] getPerfiles(int intOpcion, int intCodigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getPerfiles", ReplyAction="http://tempuri.org/IServicioGeneral/getPerfilesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.perfiles[]> getPerfilesAsync(int intOpcion, int intCodigoPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insPerfiles", ReplyAction="http://tempuri.org/IServicioGeneral/insPerfilesResponse")]
        int insPerfiles(int intOpcion, SIVEDI.Clases.perfiles perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insPerfiles", ReplyAction="http://tempuri.org/IServicioGeneral/insPerfilesResponse")]
        System.Threading.Tasks.Task<int> insPerfilesAsync(int intOpcion, SIVEDI.Clases.perfiles perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getUsuarios", ReplyAction="http://tempuri.org/IServicioGeneral/getUsuariosResponse")]
        SIVEDI.Clases.TABLAS.usuariosTabla[] getUsuarios(int intOpcion, string LoginUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getUsuarios", ReplyAction="http://tempuri.org/IServicioGeneral/getUsuariosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.usuariosTabla[]> getUsuariosAsync(int intOpcion, string LoginUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insUsuarios", ReplyAction="http://tempuri.org/IServicioGeneral/insUsuariosResponse")]
        int insUsuarios(SIVEDI.Clases.usuarios usuarioModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insUsuarios", ReplyAction="http://tempuri.org/IServicioGeneral/insUsuariosResponse")]
        System.Threading.Tasks.Task<int> insUsuariosAsync(SIVEDI.Clases.usuarios usuarioModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTiposDocumento", ReplyAction="http://tempuri.org/IServicioGeneral/getTiposDocumentoResponse")]
        SIVEDI.Clases.TABLAS.tipoDocumentoTabla[] getTiposDocumento(int intOpcion, int intCodigoTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTiposDocumento", ReplyAction="http://tempuri.org/IServicioGeneral/getTiposDocumentoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.tipoDocumentoTabla[]> getTiposDocumentoAsync(int intOpcion, int intCodigoTipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insTipoDocumento", ReplyAction="http://tempuri.org/IServicioGeneral/insTipoDocumentoResponse")]
        int insTipoDocumento(SIVEDI.Clases.TipoDocumento TipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insTipoDocumento", ReplyAction="http://tempuri.org/IServicioGeneral/insTipoDocumentoResponse")]
        System.Threading.Tasks.Task<int> insTipoDocumentoAsync(SIVEDI.Clases.TipoDocumento TipoDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTipoCliente", ReplyAction="http://tempuri.org/IServicioGeneral/getTipoClienteResponse")]
        SIVEDI.Clases.TABLAS.TipoClienteTabla[] getTipoCliente(int intOpcion, int intCodigoTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTipoCliente", ReplyAction="http://tempuri.org/IServicioGeneral/getTipoClienteResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TipoClienteTabla[]> getTipoClienteAsync(int intOpcion, int intCodigoTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTipoClienteTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getTipoClienteTablaResponse")]
        SIVEDI.Clases.TipoCliente getTipoClienteTabla(int intOpcion, int intCodigoTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTipoClienteTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getTipoClienteTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TipoCliente> getTipoClienteTablaAsync(int intOpcion, int intCodigoTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insCliente", ReplyAction="http://tempuri.org/IServicioGeneral/insClienteResponse")]
        int insCliente(SIVEDI.Clases.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insCliente", ReplyAction="http://tempuri.org/IServicioGeneral/insClienteResponse")]
        System.Threading.Tasks.Task<int> insClienteAsync(SIVEDI.Clases.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insReferenciasCliente", ReplyAction="http://tempuri.org/IServicioGeneral/insReferenciasClienteResponse")]
        int insReferenciasCliente(SIVEDI.Clases.ReferenciaCliente referenciaCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insReferenciasCliente", ReplyAction="http://tempuri.org/IServicioGeneral/insReferenciasClienteResponse")]
        System.Threading.Tasks.Task<int> insReferenciasClienteAsync(SIVEDI.Clases.ReferenciaCliente referenciaCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insTipoCliente", ReplyAction="http://tempuri.org/IServicioGeneral/insTipoClienteResponse")]
        int insTipoCliente(SIVEDI.Clases.TipoCliente tipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insTipoCliente", ReplyAction="http://tempuri.org/IServicioGeneral/insTipoClienteResponse")]
        System.Threading.Tasks.Task<int> insTipoClienteAsync(SIVEDI.Clases.TipoCliente tipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getUnidadMedida", ReplyAction="http://tempuri.org/IServicioGeneral/getUnidadMedidaResponse")]
        SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[] getUnidadMedida(int intOpcion, int intCodigoUnidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getUnidadMedida", ReplyAction="http://tempuri.org/IServicioGeneral/getUnidadMedidaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[]> getUnidadMedidaAsync(int intOpcion, int intCodigoUnidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insUnidadMedida", ReplyAction="http://tempuri.org/IServicioGeneral/insUnidadMedidaResponse")]
        int insUnidadMedida(SIVEDI.Clases.UnidadMedida unidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insUnidadMedida", ReplyAction="http://tempuri.org/IServicioGeneral/insUnidadMedidaResponse")]
        System.Threading.Tasks.Task<int> insUnidadMedidaAsync(SIVEDI.Clases.UnidadMedida unidadMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/GetGeneros", ReplyAction="http://tempuri.org/IServicioGeneral/GetGenerosResponse")]
        SIVEDI.Clases.TABLAS.GenerosTabla[] GetGeneros(int intOpcion, int intCodigoGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/GetGeneros", ReplyAction="http://tempuri.org/IServicioGeneral/GetGenerosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.GenerosTabla[]> GetGenerosAsync(int intOpcion, int intCodigoGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insGeneros", ReplyAction="http://tempuri.org/IServicioGeneral/insGenerosResponse")]
        int insGeneros(SIVEDI.Clases.Generos generos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insGeneros", ReplyAction="http://tempuri.org/IServicioGeneral/insGenerosResponse")]
        System.Threading.Tasks.Task<int> insGenerosAsync(SIVEDI.Clases.Generos generos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getformasIngreso", ReplyAction="http://tempuri.org/IServicioGeneral/getformasIngresoResponse")]
        SIVEDI.Clases.TABLAS.FormasIngresoTabla[] getformasIngreso(int intOpcion, int intCodigoFormaIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getformasIngreso", ReplyAction="http://tempuri.org/IServicioGeneral/getformasIngresoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.FormasIngresoTabla[]> getformasIngresoAsync(int intOpcion, int intCodigoFormaIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insFormasIngreso", ReplyAction="http://tempuri.org/IServicioGeneral/insFormasIngresoResponse")]
        int insFormasIngreso(SIVEDI.Clases.formasIngreso formasIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insFormasIngreso", ReplyAction="http://tempuri.org/IServicioGeneral/insFormasIngresoResponse")]
        System.Threading.Tasks.Task<int> insFormasIngresoAsync(SIVEDI.Clases.formasIngreso formasIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getEstadoCivil", ReplyAction="http://tempuri.org/IServicioGeneral/getEstadoCivilResponse")]
        SIVEDI.Clases.TABLAS.EstadoCivilTabla[] getEstadoCivil(int intOpcion, int intCodigoEstadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getEstadoCivil", ReplyAction="http://tempuri.org/IServicioGeneral/getEstadoCivilResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoCivilTabla[]> getEstadoCivilAsync(int intOpcion, int intCodigoEstadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insEstadoCivil", ReplyAction="http://tempuri.org/IServicioGeneral/insEstadoCivilResponse")]
        int insEstadoCivil(SIVEDI.Clases.EstadoCivil estadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insEstadoCivil", ReplyAction="http://tempuri.org/IServicioGeneral/insEstadoCivilResponse")]
        System.Threading.Tasks.Task<int> insEstadoCivilAsync(SIVEDI.Clases.EstadoCivil estadoCivil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getEstadoActividad", ReplyAction="http://tempuri.org/IServicioGeneral/getEstadoActividadResponse")]
        SIVEDI.Clases.TABLAS.EstadoActividadTabla[] getEstadoActividad(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getEstadoActividad", ReplyAction="http://tempuri.org/IServicioGeneral/getEstadoActividadResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoActividadTabla[]> getEstadoActividadAsync(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getEstadoActividadCamposTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getEstadoActividadCamposTablaResponse")]
        SIVEDI.Clases.EstadoActividad getEstadoActividadCamposTabla(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getEstadoActividadCamposTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getEstadoActividadCamposTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.EstadoActividad> getEstadoActividadCamposTablaAsync(int intOpcion, int intCodigoEstadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insEstadoActividad", ReplyAction="http://tempuri.org/IServicioGeneral/insEstadoActividadResponse")]
        int insEstadoActividad(SIVEDI.Clases.EstadoActividad estadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insEstadoActividad", ReplyAction="http://tempuri.org/IServicioGeneral/insEstadoActividadResponse")]
        System.Threading.Tasks.Task<int> insEstadoActividadAsync(SIVEDI.Clases.EstadoActividad estadoActividad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCampanas", ReplyAction="http://tempuri.org/IServicioGeneral/getCampanasResponse")]
        SIVEDI.Clases.TABLAS.CampanasTabla[] getCampanas(int intOpcion, int intCodigoCampana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCampanas", ReplyAction="http://tempuri.org/IServicioGeneral/getCampanasResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CampanasTabla[]> getCampanasAsync(int intOpcion, int intCodigoCampana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insCampanas", ReplyAction="http://tempuri.org/IServicioGeneral/insCampanasResponse")]
        int insCampanas(SIVEDI.Clases.campanas Campanas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insCampanas", ReplyAction="http://tempuri.org/IServicioGeneral/insCampanasResponse")]
        System.Threading.Tasks.Task<int> insCampanasAsync(SIVEDI.Clases.campanas Campanas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getPaises", ReplyAction="http://tempuri.org/IServicioGeneral/getPaisesResponse")]
        SIVEDI.Clases.TABLAS.PaisTabla[] getPaises(int intOpcion, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getPaises", ReplyAction="http://tempuri.org/IServicioGeneral/getPaisesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PaisTabla[]> getPaisesAsync(int intOpcion, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insPaises", ReplyAction="http://tempuri.org/IServicioGeneral/insPaisesResponse")]
        int insPaises(SIVEDI.Clases.Pais pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insPaises", ReplyAction="http://tempuri.org/IServicioGeneral/insPaisesResponse")]
        System.Threading.Tasks.Task<int> insPaisesAsync(SIVEDI.Clases.Pais pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getDepartamentos", ReplyAction="http://tempuri.org/IServicioGeneral/getDepartamentosResponse")]
        SIVEDI.Clases.TABLAS.DepartamentoTabla[] getDepartamentos(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getDepartamentos", ReplyAction="http://tempuri.org/IServicioGeneral/getDepartamentosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.DepartamentoTabla[]> getDepartamentosAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getDepartamentoTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getDepartamentoTablaResponse")]
        SIVEDI.Clases.Departamentos getDepartamentoTabla(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getDepartamentoTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getDepartamentoTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.Departamentos> getDepartamentoTablaAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insDepartamento", ReplyAction="http://tempuri.org/IServicioGeneral/insDepartamentoResponse")]
        int insDepartamento(SIVEDI.Clases.Departamentos departamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insDepartamento", ReplyAction="http://tempuri.org/IServicioGeneral/insDepartamentoResponse")]
        System.Threading.Tasks.Task<int> insDepartamentoAsync(SIVEDI.Clases.Departamentos departamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCiudades", ReplyAction="http://tempuri.org/IServicioGeneral/getCiudadesResponse")]
        SIVEDI.Clases.TABLAS.CiudadesTabla[] getCiudades(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCiudades", ReplyAction="http://tempuri.org/IServicioGeneral/getCiudadesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CiudadesTabla[]> getCiudadesAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCiudadesTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getCiudadesTablaResponse")]
        SIVEDI.Clases.Ciudades getCiudadesTabla(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCiudadesTabla", ReplyAction="http://tempuri.org/IServicioGeneral/getCiudadesTablaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.Ciudades> getCiudadesTablaAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insCiudades", ReplyAction="http://tempuri.org/IServicioGeneral/insCiudadesResponse")]
        int insCiudades(SIVEDI.Clases.Ciudades ciudades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insCiudades", ReplyAction="http://tempuri.org/IServicioGeneral/insCiudadesResponse")]
        System.Threading.Tasks.Task<int> insCiudadesAsync(SIVEDI.Clases.Ciudades ciudades);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getClaseResponsable", ReplyAction="http://tempuri.org/IServicioGeneral/getClaseResponsableResponse")]
        SIVEDI.Clases.TABLAS.ClaseResponsableTabla[] getClaseResponsable(int intOpcion, int intCodigoClaseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getClaseResponsable", ReplyAction="http://tempuri.org/IServicioGeneral/getClaseResponsableResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ClaseResponsableTabla[]> getClaseResponsableAsync(int intOpcion, int intCodigoClaseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insClaseResponsable", ReplyAction="http://tempuri.org/IServicioGeneral/insClaseResponsableResponse")]
        int insClaseResponsable(SIVEDI.Clases.ClaseResponsable claseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insClaseResponsable", ReplyAction="http://tempuri.org/IServicioGeneral/insClaseResponsableResponse")]
        System.Threading.Tasks.Task<int> insClaseResponsableAsync(SIVEDI.Clases.ClaseResponsable claseResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getResponsableTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/getResponsableTerritorioResponse")]
        SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[] getResponsableTerritorio(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getResponsableTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/getResponsableTerritorioResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[]> getResponsableTerritorioAsync(int intOpcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insResponsableTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/insResponsableTerritorioResponse")]
        int insResponsableTerritorio(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insResponsableTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/insResponsableTerritorioResponse")]
        System.Threading.Tasks.Task<int> insResponsableTerritorioAsync(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getResponsableFiltro", ReplyAction="http://tempuri.org/IServicioGeneral/getResponsableFiltroResponse")]
        SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[] getResponsableFiltro(string strIdentificacion, string strNombreResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getResponsableFiltro", ReplyAction="http://tempuri.org/IServicioGeneral/getResponsableFiltroResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[]> getResponsableFiltroAsync(string strIdentificacion, string strNombreResponsable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getRegionales", ReplyAction="http://tempuri.org/IServicioGeneral/getRegionalesResponse")]
        SIVEDI.Clases.TABLAS.RegionalesTabla[] getRegionales(int intOpcion, int intCodigoRegional, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getRegionales", ReplyAction="http://tempuri.org/IServicioGeneral/getRegionalesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.RegionalesTabla[]> getRegionalesAsync(int intOpcion, int intCodigoRegional, int intCodigoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insRegionales", ReplyAction="http://tempuri.org/IServicioGeneral/insRegionalesResponse")]
        int insRegionales(SIVEDI.Clases.Regionales regionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insRegionales", ReplyAction="http://tempuri.org/IServicioGeneral/insRegionalesResponse")]
        System.Threading.Tasks.Task<int> insRegionalesAsync(SIVEDI.Clases.Regionales regionales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getZonas", ReplyAction="http://tempuri.org/IServicioGeneral/getZonasResponse")]
        SIVEDI.Clases.TABLAS.ZonasTabla[] getZonas(int intOpcion, string strCodigoRegional, string strCodigoZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getZonas", ReplyAction="http://tempuri.org/IServicioGeneral/getZonasResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ZonasTabla[]> getZonasAsync(int intOpcion, string strCodigoRegional, string strCodigoZona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insZonas", ReplyAction="http://tempuri.org/IServicioGeneral/insZonasResponse")]
        int insZonas(SIVEDI.Clases.Zonas zonas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insZonas", ReplyAction="http://tempuri.org/IServicioGeneral/insZonasResponse")]
        System.Threading.Tasks.Task<int> insZonasAsync(SIVEDI.Clases.Zonas zonas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getSecciones", ReplyAction="http://tempuri.org/IServicioGeneral/getSeccionesResponse")]
        SIVEDI.Clases.TABLAS.SeccionesTabla[] getSecciones(int intOpcion, string strCodigoZona, string strCodigoSeccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getSecciones", ReplyAction="http://tempuri.org/IServicioGeneral/getSeccionesResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.SeccionesTabla[]> getSeccionesAsync(int intOpcion, string strCodigoZona, string strCodigoSeccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getSeccionFiltro", ReplyAction="http://tempuri.org/IServicioGeneral/getSeccionFiltroResponse")]
        SIVEDI.Clases.TABLAS.SeccionFiltro getSeccionFiltro(int intOpcion, string strCodigoSeccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getSeccionFiltro", ReplyAction="http://tempuri.org/IServicioGeneral/getSeccionFiltroResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.SeccionFiltro> getSeccionFiltroAsync(int intOpcion, string strCodigoSeccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insSecciones", ReplyAction="http://tempuri.org/IServicioGeneral/insSeccionesResponse")]
        int insSecciones(SIVEDI.Clases.Secciones secciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insSecciones", ReplyAction="http://tempuri.org/IServicioGeneral/insSeccionesResponse")]
        System.Threading.Tasks.Task<int> insSeccionesAsync(SIVEDI.Clases.Secciones secciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/getTerritorioResponse")]
        SIVEDI.Clases.TABLAS.TerritorioTabla[] getTerritorio(int intOpcion, string strCodigoSeccion, string strCodigoTerritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/getTerritorioResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TerritorioTabla[]> getTerritorioAsync(int intOpcion, string strCodigoSeccion, string strCodigoTerritorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTerritorioFiltro", ReplyAction="http://tempuri.org/IServicioGeneral/getTerritorioFiltroResponse")]
        SIVEDI.Clases.TABLAS.TerritorioFiltro getTerritorioFiltro(int intOpcion, string strCodigoTerrirorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTerritorioFiltro", ReplyAction="http://tempuri.org/IServicioGeneral/getTerritorioFiltroResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TerritorioFiltro> getTerritorioFiltroAsync(int intOpcion, string strCodigoTerrirorio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/insTerritorioResponse")]
        int insTerritorio(SIVEDI.Clases.Territorios territorios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insTerritorio", ReplyAction="http://tempuri.org/IServicioGeneral/insTerritorioResponse")]
        System.Threading.Tasks.Task<int> insTerritorioAsync(SIVEDI.Clases.Territorios territorios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getConsultaCliente", ReplyAction="http://tempuri.org/IServicioGeneral/getConsultaClienteResponse")]
        SIVEDI.Clases.TABLAS.ClienteConsultaTabla getConsultaCliente(string strIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getConsultaCliente", ReplyAction="http://tempuri.org/IServicioGeneral/getConsultaClienteResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ClienteConsultaTabla> getConsultaClienteAsync(string strIdentificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getReferenciaCliente", ReplyAction="http://tempuri.org/IServicioGeneral/getReferenciaClienteResponse")]
        SIVEDI.Clases.TABLAS.ReferenciaClienteTabla[] getReferenciaCliente(int intCodigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getReferenciaCliente", ReplyAction="http://tempuri.org/IServicioGeneral/getReferenciaClienteResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ReferenciaClienteTabla[]> getReferenciaClienteAsync(int intCodigoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTipoReferencia", ReplyAction="http://tempuri.org/IServicioGeneral/getTipoReferenciaResponse")]
        SIVEDI.Clases.TipoReferencia[] getTipoReferencia(int intOpcion, int intCodigoTipoReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getTipoReferencia", ReplyAction="http://tempuri.org/IServicioGeneral/getTipoReferenciaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TipoReferencia[]> getTipoReferenciaAsync(int intOpcion, int intCodigoTipoReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getFormaPago", ReplyAction="http://tempuri.org/IServicioGeneral/getFormaPagoResponse")]
        SIVEDI.Clases.FormasPago[] getFormaPago(int intOpcion, int intCodigoformaPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getFormaPago", ReplyAction="http://tempuri.org/IServicioGeneral/getFormaPagoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.FormasPago[]> getFormaPagoAsync(int intOpcion, int intCodigoformaPago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCupoMinimoCredito", ReplyAction="http://tempuri.org/IServicioGeneral/getCupoMinimoCreditoResponse")]
        SIVEDI.Clases.CupoMinimo getCupoMinimoCredito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getCupoMinimoCredito", ReplyAction="http://tempuri.org/IServicioGeneral/getCupoMinimoCreditoResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.CupoMinimo> getCupoMinimoCreditoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getProductos", ReplyAction="http://tempuri.org/IServicioGeneral/getProductosResponse")]
        SIVEDI.Clases.TABLAS.ProductoTabla[] getProductos(int intOpcion, int intCodigoProducto, string Referencia, int intCodigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getProductos", ReplyAction="http://tempuri.org/IServicioGeneral/getProductosResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ProductoTabla[]> getProductosAsync(int intOpcion, int intCodigoProducto, string Referencia, int intCodigoVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getProductosCodigoVenta", ReplyAction="http://tempuri.org/IServicioGeneral/getProductosCodigoVentaResponse")]
        SIVEDI.Clases.ProductoCodigoVenta[] getProductosCodigoVenta(int intOpcion, string strCodigoVenta, int CodigoLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/getProductosCodigoVenta", ReplyAction="http://tempuri.org/IServicioGeneral/getProductosCodigoVentaResponse")]
        System.Threading.Tasks.Task<SIVEDI.Clases.ProductoCodigoVenta[]> getProductosCodigoVentaAsync(int intOpcion, string strCodigoVenta, int CodigoLista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insProducto", ReplyAction="http://tempuri.org/IServicioGeneral/insProductoResponse")]
        int insProducto(SIVEDI.Clases.Productos productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGeneral/insProducto", ReplyAction="http://tempuri.org/IServicioGeneral/insProductoResponse")]
        System.Threading.Tasks.Task<int> insProductoAsync(SIVEDI.Clases.Productos productos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGeneralChannel : SIVEDI.ServicioGeneral.IServicioGeneral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGeneralClient : System.ServiceModel.ClientBase<SIVEDI.ServicioGeneral.IServicioGeneral>, SIVEDI.ServicioGeneral.IServicioGeneral {
        
        public ServicioGeneralClient() {
        }
        
        public ServicioGeneralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGeneralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIVEDI.Clases.LoginUsuario ingresaAplicativo(string strUser, string strPassword) {
            return base.Channel.ingresaAplicativo(strUser, strPassword);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.LoginUsuario> ingresaAplicativoAsync(string strUser, string strPassword) {
            return base.Channel.ingresaAplicativoAsync(strUser, strPassword);
        }
        
        public SIVEDI.Clases.moduloPadre[] getModuloPadre(int intOpcion) {
            return base.Channel.getModuloPadre(intOpcion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.moduloPadre[]> getModuloPadreAsync(int intOpcion) {
            return base.Channel.getModuloPadreAsync(intOpcion);
        }
        
        public SIVEDI.Clases.moduloHijo[] getModuloHijo(int intCodigoUsuario, int intCodigoPadre) {
            return base.Channel.getModuloHijo(intCodigoUsuario, intCodigoPadre);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.moduloHijo[]> getModuloHijoAsync(int intCodigoUsuario, int intCodigoPadre) {
            return base.Channel.getModuloHijoAsync(intCodigoUsuario, intCodigoPadre);
        }
        
        public SIVEDI.Clases.perfiles[] getPerfiles(int intOpcion, int intCodigoPerfil) {
            return base.Channel.getPerfiles(intOpcion, intCodigoPerfil);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.perfiles[]> getPerfilesAsync(int intOpcion, int intCodigoPerfil) {
            return base.Channel.getPerfilesAsync(intOpcion, intCodigoPerfil);
        }
        
        public int insPerfiles(int intOpcion, SIVEDI.Clases.perfiles perfil) {
            return base.Channel.insPerfiles(intOpcion, perfil);
        }
        
        public System.Threading.Tasks.Task<int> insPerfilesAsync(int intOpcion, SIVEDI.Clases.perfiles perfil) {
            return base.Channel.insPerfilesAsync(intOpcion, perfil);
        }
        
        public SIVEDI.Clases.TABLAS.usuariosTabla[] getUsuarios(int intOpcion, string LoginUsuario) {
            return base.Channel.getUsuarios(intOpcion, LoginUsuario);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.usuariosTabla[]> getUsuariosAsync(int intOpcion, string LoginUsuario) {
            return base.Channel.getUsuariosAsync(intOpcion, LoginUsuario);
        }
        
        public int insUsuarios(SIVEDI.Clases.usuarios usuarioModel) {
            return base.Channel.insUsuarios(usuarioModel);
        }
        
        public System.Threading.Tasks.Task<int> insUsuariosAsync(SIVEDI.Clases.usuarios usuarioModel) {
            return base.Channel.insUsuariosAsync(usuarioModel);
        }
        
        public SIVEDI.Clases.TABLAS.tipoDocumentoTabla[] getTiposDocumento(int intOpcion, int intCodigoTipoDocumento) {
            return base.Channel.getTiposDocumento(intOpcion, intCodigoTipoDocumento);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.tipoDocumentoTabla[]> getTiposDocumentoAsync(int intOpcion, int intCodigoTipoDocumento) {
            return base.Channel.getTiposDocumentoAsync(intOpcion, intCodigoTipoDocumento);
        }
        
        public int insTipoDocumento(SIVEDI.Clases.TipoDocumento TipoDocumento) {
            return base.Channel.insTipoDocumento(TipoDocumento);
        }
        
        public System.Threading.Tasks.Task<int> insTipoDocumentoAsync(SIVEDI.Clases.TipoDocumento TipoDocumento) {
            return base.Channel.insTipoDocumentoAsync(TipoDocumento);
        }
        
        public SIVEDI.Clases.TABLAS.TipoClienteTabla[] getTipoCliente(int intOpcion, int intCodigoTipoCliente) {
            return base.Channel.getTipoCliente(intOpcion, intCodigoTipoCliente);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TipoClienteTabla[]> getTipoClienteAsync(int intOpcion, int intCodigoTipoCliente) {
            return base.Channel.getTipoClienteAsync(intOpcion, intCodigoTipoCliente);
        }
        
        public SIVEDI.Clases.TipoCliente getTipoClienteTabla(int intOpcion, int intCodigoTipoCliente) {
            return base.Channel.getTipoClienteTabla(intOpcion, intCodigoTipoCliente);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TipoCliente> getTipoClienteTablaAsync(int intOpcion, int intCodigoTipoCliente) {
            return base.Channel.getTipoClienteTablaAsync(intOpcion, intCodigoTipoCliente);
        }
        
        public int insCliente(SIVEDI.Clases.Cliente cliente) {
            return base.Channel.insCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<int> insClienteAsync(SIVEDI.Clases.Cliente cliente) {
            return base.Channel.insClienteAsync(cliente);
        }
        
        public int insReferenciasCliente(SIVEDI.Clases.ReferenciaCliente referenciaCliente) {
            return base.Channel.insReferenciasCliente(referenciaCliente);
        }
        
        public System.Threading.Tasks.Task<int> insReferenciasClienteAsync(SIVEDI.Clases.ReferenciaCliente referenciaCliente) {
            return base.Channel.insReferenciasClienteAsync(referenciaCliente);
        }
        
        public int insTipoCliente(SIVEDI.Clases.TipoCliente tipoCliente) {
            return base.Channel.insTipoCliente(tipoCliente);
        }
        
        public System.Threading.Tasks.Task<int> insTipoClienteAsync(SIVEDI.Clases.TipoCliente tipoCliente) {
            return base.Channel.insTipoClienteAsync(tipoCliente);
        }
        
        public SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[] getUnidadMedida(int intOpcion, int intCodigoUnidadMedida) {
            return base.Channel.getUnidadMedida(intOpcion, intCodigoUnidadMedida);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.UnidadesMedidaTabla[]> getUnidadMedidaAsync(int intOpcion, int intCodigoUnidadMedida) {
            return base.Channel.getUnidadMedidaAsync(intOpcion, intCodigoUnidadMedida);
        }
        
        public int insUnidadMedida(SIVEDI.Clases.UnidadMedida unidadMedida) {
            return base.Channel.insUnidadMedida(unidadMedida);
        }
        
        public System.Threading.Tasks.Task<int> insUnidadMedidaAsync(SIVEDI.Clases.UnidadMedida unidadMedida) {
            return base.Channel.insUnidadMedidaAsync(unidadMedida);
        }
        
        public SIVEDI.Clases.TABLAS.GenerosTabla[] GetGeneros(int intOpcion, int intCodigoGenero) {
            return base.Channel.GetGeneros(intOpcion, intCodigoGenero);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.GenerosTabla[]> GetGenerosAsync(int intOpcion, int intCodigoGenero) {
            return base.Channel.GetGenerosAsync(intOpcion, intCodigoGenero);
        }
        
        public int insGeneros(SIVEDI.Clases.Generos generos) {
            return base.Channel.insGeneros(generos);
        }
        
        public System.Threading.Tasks.Task<int> insGenerosAsync(SIVEDI.Clases.Generos generos) {
            return base.Channel.insGenerosAsync(generos);
        }
        
        public SIVEDI.Clases.TABLAS.FormasIngresoTabla[] getformasIngreso(int intOpcion, int intCodigoFormaIngreso) {
            return base.Channel.getformasIngreso(intOpcion, intCodigoFormaIngreso);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.FormasIngresoTabla[]> getformasIngresoAsync(int intOpcion, int intCodigoFormaIngreso) {
            return base.Channel.getformasIngresoAsync(intOpcion, intCodigoFormaIngreso);
        }
        
        public int insFormasIngreso(SIVEDI.Clases.formasIngreso formasIngreso) {
            return base.Channel.insFormasIngreso(formasIngreso);
        }
        
        public System.Threading.Tasks.Task<int> insFormasIngresoAsync(SIVEDI.Clases.formasIngreso formasIngreso) {
            return base.Channel.insFormasIngresoAsync(formasIngreso);
        }
        
        public SIVEDI.Clases.TABLAS.EstadoCivilTabla[] getEstadoCivil(int intOpcion, int intCodigoEstadoCivil) {
            return base.Channel.getEstadoCivil(intOpcion, intCodigoEstadoCivil);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoCivilTabla[]> getEstadoCivilAsync(int intOpcion, int intCodigoEstadoCivil) {
            return base.Channel.getEstadoCivilAsync(intOpcion, intCodigoEstadoCivil);
        }
        
        public int insEstadoCivil(SIVEDI.Clases.EstadoCivil estadoCivil) {
            return base.Channel.insEstadoCivil(estadoCivil);
        }
        
        public System.Threading.Tasks.Task<int> insEstadoCivilAsync(SIVEDI.Clases.EstadoCivil estadoCivil) {
            return base.Channel.insEstadoCivilAsync(estadoCivil);
        }
        
        public SIVEDI.Clases.TABLAS.EstadoActividadTabla[] getEstadoActividad(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividad(intOpcion, intCodigoEstadoActividad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.EstadoActividadTabla[]> getEstadoActividadAsync(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividadAsync(intOpcion, intCodigoEstadoActividad);
        }
        
        public SIVEDI.Clases.EstadoActividad getEstadoActividadCamposTabla(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividadCamposTabla(intOpcion, intCodigoEstadoActividad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.EstadoActividad> getEstadoActividadCamposTablaAsync(int intOpcion, int intCodigoEstadoActividad) {
            return base.Channel.getEstadoActividadCamposTablaAsync(intOpcion, intCodigoEstadoActividad);
        }
        
        public int insEstadoActividad(SIVEDI.Clases.EstadoActividad estadoActividad) {
            return base.Channel.insEstadoActividad(estadoActividad);
        }
        
        public System.Threading.Tasks.Task<int> insEstadoActividadAsync(SIVEDI.Clases.EstadoActividad estadoActividad) {
            return base.Channel.insEstadoActividadAsync(estadoActividad);
        }
        
        public SIVEDI.Clases.TABLAS.CampanasTabla[] getCampanas(int intOpcion, int intCodigoCampana) {
            return base.Channel.getCampanas(intOpcion, intCodigoCampana);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CampanasTabla[]> getCampanasAsync(int intOpcion, int intCodigoCampana) {
            return base.Channel.getCampanasAsync(intOpcion, intCodigoCampana);
        }
        
        public int insCampanas(SIVEDI.Clases.campanas Campanas) {
            return base.Channel.insCampanas(Campanas);
        }
        
        public System.Threading.Tasks.Task<int> insCampanasAsync(SIVEDI.Clases.campanas Campanas) {
            return base.Channel.insCampanasAsync(Campanas);
        }
        
        public SIVEDI.Clases.TABLAS.PaisTabla[] getPaises(int intOpcion, int intCodigoPais) {
            return base.Channel.getPaises(intOpcion, intCodigoPais);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.PaisTabla[]> getPaisesAsync(int intOpcion, int intCodigoPais) {
            return base.Channel.getPaisesAsync(intOpcion, intCodigoPais);
        }
        
        public int insPaises(SIVEDI.Clases.Pais pais) {
            return base.Channel.insPaises(pais);
        }
        
        public System.Threading.Tasks.Task<int> insPaisesAsync(SIVEDI.Clases.Pais pais) {
            return base.Channel.insPaisesAsync(pais);
        }
        
        public SIVEDI.Clases.TABLAS.DepartamentoTabla[] getDepartamentos(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentos(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.DepartamentoTabla[]> getDepartamentosAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentosAsync(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public SIVEDI.Clases.Departamentos getDepartamentoTabla(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentoTabla(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.Departamentos> getDepartamentoTablaAsync(int intOpcion, int intCodigoPais, int intCodigoDepartamento) {
            return base.Channel.getDepartamentoTablaAsync(intOpcion, intCodigoPais, intCodigoDepartamento);
        }
        
        public int insDepartamento(SIVEDI.Clases.Departamentos departamentos) {
            return base.Channel.insDepartamento(departamentos);
        }
        
        public System.Threading.Tasks.Task<int> insDepartamentoAsync(SIVEDI.Clases.Departamentos departamentos) {
            return base.Channel.insDepartamentoAsync(departamentos);
        }
        
        public SIVEDI.Clases.TABLAS.CiudadesTabla[] getCiudades(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudades(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.CiudadesTabla[]> getCiudadesAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudadesAsync(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public SIVEDI.Clases.Ciudades getCiudadesTabla(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudadesTabla(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.Ciudades> getCiudadesTablaAsync(int intOpcion, int intCodigoDepartamento, int intCodigoCiudad) {
            return base.Channel.getCiudadesTablaAsync(intOpcion, intCodigoDepartamento, intCodigoCiudad);
        }
        
        public int insCiudades(SIVEDI.Clases.Ciudades ciudades) {
            return base.Channel.insCiudades(ciudades);
        }
        
        public System.Threading.Tasks.Task<int> insCiudadesAsync(SIVEDI.Clases.Ciudades ciudades) {
            return base.Channel.insCiudadesAsync(ciudades);
        }
        
        public SIVEDI.Clases.TABLAS.ClaseResponsableTabla[] getClaseResponsable(int intOpcion, int intCodigoClaseResponsable) {
            return base.Channel.getClaseResponsable(intOpcion, intCodigoClaseResponsable);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ClaseResponsableTabla[]> getClaseResponsableAsync(int intOpcion, int intCodigoClaseResponsable) {
            return base.Channel.getClaseResponsableAsync(intOpcion, intCodigoClaseResponsable);
        }
        
        public int insClaseResponsable(SIVEDI.Clases.ClaseResponsable claseResponsable) {
            return base.Channel.insClaseResponsable(claseResponsable);
        }
        
        public System.Threading.Tasks.Task<int> insClaseResponsableAsync(SIVEDI.Clases.ClaseResponsable claseResponsable) {
            return base.Channel.insClaseResponsableAsync(claseResponsable);
        }
        
        public SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[] getResponsableTerritorio(int intOpcion) {
            return base.Channel.getResponsableTerritorio(intOpcion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioTabla[]> getResponsableTerritorioAsync(int intOpcion) {
            return base.Channel.getResponsableTerritorioAsync(intOpcion);
        }
        
        public int insResponsableTerritorio(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio) {
            return base.Channel.insResponsableTerritorio(responsableTerritorio);
        }
        
        public System.Threading.Tasks.Task<int> insResponsableTerritorioAsync(SIVEDI.Clases.ResponsableTerritorio responsableTerritorio) {
            return base.Channel.insResponsableTerritorioAsync(responsableTerritorio);
        }
        
        public SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[] getResponsableFiltro(string strIdentificacion, string strNombreResponsable) {
            return base.Channel.getResponsableFiltro(strIdentificacion, strNombreResponsable);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ResponsableTerritorioFiltro[]> getResponsableFiltroAsync(string strIdentificacion, string strNombreResponsable) {
            return base.Channel.getResponsableFiltroAsync(strIdentificacion, strNombreResponsable);
        }
        
        public SIVEDI.Clases.TABLAS.RegionalesTabla[] getRegionales(int intOpcion, int intCodigoRegional, int intCodigoPais) {
            return base.Channel.getRegionales(intOpcion, intCodigoRegional, intCodigoPais);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.RegionalesTabla[]> getRegionalesAsync(int intOpcion, int intCodigoRegional, int intCodigoPais) {
            return base.Channel.getRegionalesAsync(intOpcion, intCodigoRegional, intCodigoPais);
        }
        
        public int insRegionales(SIVEDI.Clases.Regionales regionales) {
            return base.Channel.insRegionales(regionales);
        }
        
        public System.Threading.Tasks.Task<int> insRegionalesAsync(SIVEDI.Clases.Regionales regionales) {
            return base.Channel.insRegionalesAsync(regionales);
        }
        
        public SIVEDI.Clases.TABLAS.ZonasTabla[] getZonas(int intOpcion, string strCodigoRegional, string strCodigoZona) {
            return base.Channel.getZonas(intOpcion, strCodigoRegional, strCodigoZona);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ZonasTabla[]> getZonasAsync(int intOpcion, string strCodigoRegional, string strCodigoZona) {
            return base.Channel.getZonasAsync(intOpcion, strCodigoRegional, strCodigoZona);
        }
        
        public int insZonas(SIVEDI.Clases.Zonas zonas) {
            return base.Channel.insZonas(zonas);
        }
        
        public System.Threading.Tasks.Task<int> insZonasAsync(SIVEDI.Clases.Zonas zonas) {
            return base.Channel.insZonasAsync(zonas);
        }
        
        public SIVEDI.Clases.TABLAS.SeccionesTabla[] getSecciones(int intOpcion, string strCodigoZona, string strCodigoSeccion) {
            return base.Channel.getSecciones(intOpcion, strCodigoZona, strCodigoSeccion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.SeccionesTabla[]> getSeccionesAsync(int intOpcion, string strCodigoZona, string strCodigoSeccion) {
            return base.Channel.getSeccionesAsync(intOpcion, strCodigoZona, strCodigoSeccion);
        }
        
        public SIVEDI.Clases.TABLAS.SeccionFiltro getSeccionFiltro(int intOpcion, string strCodigoSeccion) {
            return base.Channel.getSeccionFiltro(intOpcion, strCodigoSeccion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.SeccionFiltro> getSeccionFiltroAsync(int intOpcion, string strCodigoSeccion) {
            return base.Channel.getSeccionFiltroAsync(intOpcion, strCodigoSeccion);
        }
        
        public int insSecciones(SIVEDI.Clases.Secciones secciones) {
            return base.Channel.insSecciones(secciones);
        }
        
        public System.Threading.Tasks.Task<int> insSeccionesAsync(SIVEDI.Clases.Secciones secciones) {
            return base.Channel.insSeccionesAsync(secciones);
        }
        
        public SIVEDI.Clases.TABLAS.TerritorioTabla[] getTerritorio(int intOpcion, string strCodigoSeccion, string strCodigoTerritorio) {
            return base.Channel.getTerritorio(intOpcion, strCodigoSeccion, strCodigoTerritorio);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TerritorioTabla[]> getTerritorioAsync(int intOpcion, string strCodigoSeccion, string strCodigoTerritorio) {
            return base.Channel.getTerritorioAsync(intOpcion, strCodigoSeccion, strCodigoTerritorio);
        }
        
        public SIVEDI.Clases.TABLAS.TerritorioFiltro getTerritorioFiltro(int intOpcion, string strCodigoTerrirorio) {
            return base.Channel.getTerritorioFiltro(intOpcion, strCodigoTerrirorio);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.TerritorioFiltro> getTerritorioFiltroAsync(int intOpcion, string strCodigoTerrirorio) {
            return base.Channel.getTerritorioFiltroAsync(intOpcion, strCodigoTerrirorio);
        }
        
        public int insTerritorio(SIVEDI.Clases.Territorios territorios) {
            return base.Channel.insTerritorio(territorios);
        }
        
        public System.Threading.Tasks.Task<int> insTerritorioAsync(SIVEDI.Clases.Territorios territorios) {
            return base.Channel.insTerritorioAsync(territorios);
        }
        
        public SIVEDI.Clases.TABLAS.ClienteConsultaTabla getConsultaCliente(string strIdentificacion) {
            return base.Channel.getConsultaCliente(strIdentificacion);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ClienteConsultaTabla> getConsultaClienteAsync(string strIdentificacion) {
            return base.Channel.getConsultaClienteAsync(strIdentificacion);
        }
        
        public SIVEDI.Clases.TABLAS.ReferenciaClienteTabla[] getReferenciaCliente(int intCodigoCliente) {
            return base.Channel.getReferenciaCliente(intCodigoCliente);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ReferenciaClienteTabla[]> getReferenciaClienteAsync(int intCodigoCliente) {
            return base.Channel.getReferenciaClienteAsync(intCodigoCliente);
        }
        
        public SIVEDI.Clases.TipoReferencia[] getTipoReferencia(int intOpcion, int intCodigoTipoReferencia) {
            return base.Channel.getTipoReferencia(intOpcion, intCodigoTipoReferencia);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TipoReferencia[]> getTipoReferenciaAsync(int intOpcion, int intCodigoTipoReferencia) {
            return base.Channel.getTipoReferenciaAsync(intOpcion, intCodigoTipoReferencia);
        }
        
        public SIVEDI.Clases.FormasPago[] getFormaPago(int intOpcion, int intCodigoformaPago) {
            return base.Channel.getFormaPago(intOpcion, intCodigoformaPago);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.FormasPago[]> getFormaPagoAsync(int intOpcion, int intCodigoformaPago) {
            return base.Channel.getFormaPagoAsync(intOpcion, intCodigoformaPago);
        }
        
        public SIVEDI.Clases.CupoMinimo getCupoMinimoCredito() {
            return base.Channel.getCupoMinimoCredito();
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.CupoMinimo> getCupoMinimoCreditoAsync() {
            return base.Channel.getCupoMinimoCreditoAsync();
        }
        
        public SIVEDI.Clases.TABLAS.ProductoTabla[] getProductos(int intOpcion, int intCodigoProducto, string Referencia, int intCodigoVenta) {
            return base.Channel.getProductos(intOpcion, intCodigoProducto, Referencia, intCodigoVenta);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.TABLAS.ProductoTabla[]> getProductosAsync(int intOpcion, int intCodigoProducto, string Referencia, int intCodigoVenta) {
            return base.Channel.getProductosAsync(intOpcion, intCodigoProducto, Referencia, intCodigoVenta);
        }
        
        public SIVEDI.Clases.ProductoCodigoVenta[] getProductosCodigoVenta(int intOpcion, string strCodigoVenta, int CodigoLista) {
            return base.Channel.getProductosCodigoVenta(intOpcion, strCodigoVenta, CodigoLista);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.Clases.ProductoCodigoVenta[]> getProductosCodigoVentaAsync(int intOpcion, string strCodigoVenta, int CodigoLista) {
            return base.Channel.getProductosCodigoVentaAsync(intOpcion, strCodigoVenta, CodigoLista);
        }
        
        public int insProducto(SIVEDI.Clases.Productos productos) {
            return base.Channel.insProducto(productos);
        }
        
        public System.Threading.Tasks.Task<int> insProductoAsync(SIVEDI.Clases.Productos productos) {
            return base.Channel.insProductoAsync(productos);
        }
    }
}
