//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVEDI.ServicioLiquidacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLiquidacion.IServiceLiquidacion")]
    public interface IServiceLiquidacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLiquidacion/DoWork", ReplyAction="http://tempuri.org/IServiceLiquidacion/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLiquidacion/DoWork", ReplyAction="http://tempuri.org/IServiceLiquidacion/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLiquidacion/preliquidaPedido", ReplyAction="http://tempuri.org/IServiceLiquidacion/preliquidaPedidoResponse")]
        System.Data.DataTable preliquidaPedido(System.Data.DataTable dttPedidoOriginal, int intCodigoListaPrecios, string strConexion, int intCodigoEstadoActiCliente, string strCodigoZonaCliente, int intCodigoTipoCliente, bool blnEsIngreso, string strIdentificacionCliente, int intCodigoCiudadCliente, bool blnCobraFlete, int intTipoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLiquidacion/preliquidaPedido", ReplyAction="http://tempuri.org/IServiceLiquidacion/preliquidaPedidoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> preliquidaPedidoAsync(System.Data.DataTable dttPedidoOriginal, int intCodigoListaPrecios, string strConexion, int intCodigoEstadoActiCliente, string strCodigoZonaCliente, int intCodigoTipoCliente, bool blnEsIngreso, string strIdentificacionCliente, int intCodigoCiudadCliente, bool blnCobraFlete, int intTipoCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLiquidacionChannel : SIVEDI.ServicioLiquidacion.IServiceLiquidacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLiquidacionClient : System.ServiceModel.ClientBase<SIVEDI.ServicioLiquidacion.IServiceLiquidacion>, SIVEDI.ServicioLiquidacion.IServiceLiquidacion {
        
        public ServiceLiquidacionClient() {
        }
        
        public ServiceLiquidacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLiquidacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLiquidacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLiquidacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataTable preliquidaPedido(System.Data.DataTable dttPedidoOriginal, int intCodigoListaPrecios, string strConexion, int intCodigoEstadoActiCliente, string strCodigoZonaCliente, int intCodigoTipoCliente, bool blnEsIngreso, string strIdentificacionCliente, int intCodigoCiudadCliente, bool blnCobraFlete, int intTipoCliente) {
            return base.Channel.preliquidaPedido(dttPedidoOriginal, intCodigoListaPrecios, strConexion, intCodigoEstadoActiCliente, strCodigoZonaCliente, intCodigoTipoCliente, blnEsIngreso, strIdentificacionCliente, intCodigoCiudadCliente, blnCobraFlete, intTipoCliente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> preliquidaPedidoAsync(System.Data.DataTable dttPedidoOriginal, int intCodigoListaPrecios, string strConexion, int intCodigoEstadoActiCliente, string strCodigoZonaCliente, int intCodigoTipoCliente, bool blnEsIngreso, string strIdentificacionCliente, int intCodigoCiudadCliente, bool blnCobraFlete, int intTipoCliente) {
            return base.Channel.preliquidaPedidoAsync(dttPedidoOriginal, intCodigoListaPrecios, strConexion, intCodigoEstadoActiCliente, strCodigoZonaCliente, intCodigoTipoCliente, blnEsIngreso, strIdentificacionCliente, intCodigoCiudadCliente, blnCobraFlete, intTipoCliente);
        }
    }
}
