//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVEDI.APIGeneral.ServicioGeneral {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginUsuario", Namespace="http://schemas.datacontract.org/2004/07/SIVEDI.Clases")]
    [System.SerializableAttribute()]
    public partial class LoginUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool blnCambiaPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool blnEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool blnResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intCodigoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strEmailUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool blnCambiaPassword {
            get {
                return this.blnCambiaPasswordField;
            }
            set {
                if ((this.blnCambiaPasswordField.Equals(value) != true)) {
                    this.blnCambiaPasswordField = value;
                    this.RaisePropertyChanged("blnCambiaPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool blnEstado {
            get {
                return this.blnEstadoField;
            }
            set {
                if ((this.blnEstadoField.Equals(value) != true)) {
                    this.blnEstadoField = value;
                    this.RaisePropertyChanged("blnEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool blnResultado {
            get {
                return this.blnResultadoField;
            }
            set {
                if ((this.blnResultadoField.Equals(value) != true)) {
                    this.blnResultadoField = value;
                    this.RaisePropertyChanged("blnResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCodigoPerfil {
            get {
                return this.intCodigoPerfilField;
            }
            set {
                if ((this.intCodigoPerfilField.Equals(value) != true)) {
                    this.intCodigoPerfilField = value;
                    this.RaisePropertyChanged("intCodigoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdUsuario {
            get {
                return this.intIdUsuarioField;
            }
            set {
                if ((this.intIdUsuarioField.Equals(value) != true)) {
                    this.intIdUsuarioField = value;
                    this.RaisePropertyChanged("intIdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strEmailUsuario {
            get {
                return this.strEmailUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.strEmailUsuarioField, value) != true)) {
                    this.strEmailUsuarioField = value;
                    this.RaisePropertyChanged("strEmailUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombreUsuario {
            get {
                return this.strNombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.strNombreUsuarioField, value) != true)) {
                    this.strNombreUsuarioField = value;
                    this.RaisePropertyChanged("strNombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioGeneral.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ingresaAplicativo", ReplyAction="http://tempuri.org/IService/ingresaAplicativoResponse")]
        SIVEDI.APIGeneral.ServicioGeneral.LoginUsuario ingresaAplicativo(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ingresaAplicativo", ReplyAction="http://tempuri.org/IService/ingresaAplicativoResponse")]
        System.Threading.Tasks.Task<SIVEDI.APIGeneral.ServicioGeneral.LoginUsuario> ingresaAplicativoAsync(string strUser, string strPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SIVEDI.APIGeneral.ServicioGeneral.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SIVEDI.APIGeneral.ServicioGeneral.IService>, SIVEDI.APIGeneral.ServicioGeneral.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIVEDI.APIGeneral.ServicioGeneral.LoginUsuario ingresaAplicativo(string strUser, string strPassword) {
            return base.Channel.ingresaAplicativo(strUser, strPassword);
        }
        
        public System.Threading.Tasks.Task<SIVEDI.APIGeneral.ServicioGeneral.LoginUsuario> ingresaAplicativoAsync(string strUser, string strPassword) {
            return base.Channel.ingresaAplicativoAsync(strUser, strPassword);
        }
    }
}
